### ISSUE TITLE
What is the use case for this module?

### ISSUE THREAD

**Issue by rickyhan** [anvaka/query-state#1]
Please spoonfeed me about how the idea of URL might apply to state management.

**Comment by anvaka** [comment]
Hi @rickyhan!

Imagine game of chess, where you have 32 pieces on 64 square grid. Their position at any moment of time can represent "application state". If you want to share this position with someone over the internet, instead of having to pay for a server you can just share the URL with all information about chess pieces in it, and let javascript render the chess board from the URL.

Another example could be position on the map. If you encode `x,y,z` coordinates you can send someone precise position of what you are looking at. Here are some of my examples:

* https://anvaka.github.io/complete-cloud/#?selected=what-if - the query string shares currently selected question, so you can see exact same set of words that I'm looking at.
* https://what-people-google.anvaka.com/#?x=-3535.933&y=-2775.684&w=1280&h=698&scale=9.157&q=why-is - the map is centered at the same position that it is on my screen.

Obviously, this will not work if application state is more complex than just a few key-values (in which case you'd better be off storing some keys that could help javascript fetch information from remote data source).
